### ISSUE TITLE
Menu wont show up

### ISSUE THREAD

**Issue by andrevaz15** [SerseDioRe/esx_disassemble_weapons#2]
Everything did fine, but when I press the F9 key the menu wont show up

**Comment by V3ctor2002** [comment]
@andrevaz15 any errors when starting the resurce?

**Comment by andrevaz15** [comment]
Already solved it, forgot to close, thanks anyway!

**Comment by V3ctor2002** [comment]
@andrevaz15 OK nice anyways youre welcome
